# Generated by Django 3.0.5 on 2020-05-08 00:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooleanIotDevice',
            fields=[
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('state', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'boolean_iot_device',
            },
        ),
    ]
