# Generated by Django 3.0.4 on 2020-03-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct_controll_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booleaniotdevice',
            old_name='id',
            new_name='device_id',
        ),
    ]
