# Generated by Django 3.0.4 on 2020-03-29 19:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('direct_controll_module', '0002_auto_20200329_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleaniotdevice',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('c2205f8a-119f-43e1-a686-d3a7d455a6b1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booleaniotdevice',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
