# Generated by Django 3.0.4 on 2020-03-29 19:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('direct_controll_module', '0003_auto_20200329_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleaniotdevice',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('7f0b4bc7-08a3-4aa4-a660-93c7500ae668'), editable=False, primary_key=True, serialize=False),
        ),
    ]
