# Generated by Django 3.0.4 on 2020-03-29 19:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('direct_controll_module', '0004_auto_20200329_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleaniotdevice',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('bee9270f-f6f2-4922-bafe-b4198368d78f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='booleaniotdevice',
            table='boolean_iot_device',
        ),
    ]
