# Generated by Django 3.0.4 on 2020-03-29 19:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('direct_controll_module', '0005_auto_20200329_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleaniotdevice',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('32036e98-4659-4eb1-becb-babde5154b28'), editable=False, primary_key=True, serialize=False),
        ),
    ]
