# Generated by Django 3.0.4 on 2020-03-29 19:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('direct_controll_module', '0006_auto_20200329_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleaniotdevice',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('d7fa86f9-1132-4a52-a44b-f7fb0b10feea'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booleaniotdevice',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
