# Generated by Django 3.0.4 on 2020-03-31 20:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('direct_controll_module', '0007_auto_20200329_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleaniotdevice',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('9f6f9f0c-1325-4031-9d5e-610b94bcab00'), editable=False, primary_key=True, serialize=False),
        ),
    ]
