# Generated by Django 3.0.5 on 2020-04-01 20:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('direct_controll_module', '0008_auto_20200331_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleaniotdevice',
            name='device_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
