# Generated by Django 3.0.5 on 2020-05-08 00:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FbUserModel',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fb_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('permissions', models.CharField(default='NONE', max_length=50)),
            ],
            options={
                'db_table': 'fb_user',
            },
        ),
    ]
